---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  ansible-lint
platforms:
  - name: instance
    box: tas50/windows_2016
provisioner:
  name: ansible
verifier:
  name: inspec
  enabled: false